# Generated by Django 5.2.4 on 2025-07-12 06:15

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('train_type', models.CharField(choices=[('Express', 'Express'), ('Passenger', 'Passenger'), ('Superfast', 'Superfast')], max_length=20)),
                ('running_days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3), help_text="Days when the train runs (e.g., ['Mon', 'Tue', 'Fri'])", size=7)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the train is active or soft deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Train',
                'verbose_name_plural': 'Trains',
                'ordering': ['train_number'],
            },
        ),
        migrations.CreateModel(
            name='TrainClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('General', 'General'), ('Sleeper', 'Sleeper'), ('AC', 'AC')], max_length=20)),
                ('seat_capacity', models.PositiveIntegerField(help_text='Number of seats available in this class')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='trains.train')),
            ],
            options={
                'verbose_name': 'Train Class',
                'verbose_name_plural': 'Train Classes',
                'ordering': ['train', 'class_type'],
                'unique_together': {('train', 'class_type')},
            },
        ),
    ]
