# Generated by Django 5.2.4 on 2025-07-22 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('train_type', models.CharField(choices=[('Local', 'local'), ('Fast', 'fast'), ('AC', 'ac')], max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the train is active or soft deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Train',
                'verbose_name_plural': 'Trains',
                'db_table': 'trains',
                'ordering': ['train_number'],
            },
        ),
        migrations.CreateModel(
            name='TrainSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_of_week', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('stops_with_time', models.JSONField(blank=True, default=list)),
                ('direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.routetemplate')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='trains.train')),
            ],
            options={
                'verbose_name': 'Train Schedule',
                'verbose_name_plural': 'Train Schedules',
                'db_table': 'train_schedules',
                'ordering': ['train', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TrainClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('GENERAL', 'General'), ('FC', 'fc')], max_length=20)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='trains.train')),
            ],
            options={
                'verbose_name': 'Train Class',
                'verbose_name_plural': 'Train Classes',
                'db_table': 'train_class',
                'ordering': ['train', 'class_type'],
                'unique_together': {('train', 'class_type')},
            },
        ),
    ]
