# Generated by Django 5.2.4 on 2025-07-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='train_number',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
