# Generated by Django 5.2.4 on 2025-07-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_alter_train_train_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterModelTable(
            name='train',
            table=None,
        ),
        migrations.AlterModelTable(
            name='trainclass',
            table=None,
        ),
    ]
