# Generated by Django 5.2.4 on 2025-07-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0003_alter_train_name_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
