# Generated by Django 5.2.4 on 2025-07-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0004_remove_unique_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the train is active or soft deleted'),
        ),
    ]
