# Generated by Django 5.2.4 on 2025-07-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Card'), ('UPI', 'UPI'), ('NETBANKING', 'Netbanking'), ('WALLET', 'Wallet')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='paymenttransaction',
            table=None,
        ),
    ]
