# Generated by Django 5.2.4 on 2025-07-12 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('trains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField()),
                ('booking_status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('RAC', 'Reservation Against Cancellation'), ('WL', 'Waitlist'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('quota', models.CharField(choices=[('General', 'General'), ('Tatkal', 'Tatkal'), ('Ladies', 'Ladies'), ('SeniorCitizen', 'Senior Citizen')], default='General', max_length=20)),
                ('class_type', models.CharField(choices=[('General', 'General'), ('Sleeper', 'Sleeper'), ('AC', 'AC')], default='Sleeper', max_length=20)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pnr_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_bookings', to='stations.station')),
                ('source_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_bookings', to='stations.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trains.train')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('berth_preference', models.CharField(choices=[('LB', 'Lower Berth'), ('MB', 'Middle Berth'), ('UB', 'Upper Berth'), ('SL', 'Side Lower'), ('SU', 'Side Upper')], max_length=2)),
                ('seat_number', models.CharField(blank=True, max_length=10, null=True)),
                ('booking_status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('RAC', 'Reservation Against Cancellation'), ('WL', 'Waitlist')], default='CONFIRMED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='bookingsystem.booking')),
            ],
            options={
                'verbose_name': 'Passenger',
                'verbose_name_plural': 'Passengers',
                'ordering': ['booking', 'name'],
            },
        ),
    ]
