# Generated by Django 5.2.4 on 2025-07-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('RAC', 'Reservation Against Cancellation'), ('WL', 'Waitlist'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
