# Generated by Django 5.2.4 on 2025-07-12 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('total_distance', models.FloatField(help_text='Total distance in km')),
                ('estimated_duration', models.IntegerField(help_text='Estimated duration in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_templates_destination', to='stations.station')),
                ('source_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_templates_source', to='stations.station')),
            ],
            options={
                'verbose_name': 'Route Template',
                'verbose_name_plural': 'Route Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RouteTemplateStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='Order of stops in the template')),
                ('distance_from_source', models.FloatField(help_text='Distance from source station in km')),
                ('estimated_halt_minutes', models.PositiveIntegerField(default=2, help_text='Estimated halt duration')),
                ('route_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_stops', to='routes.routetemplate')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_stops', to='stations.station')),
            ],
            options={
                'verbose_name': 'Route Template Stop',
                'verbose_name_plural': 'Route Template Stops',
                'ordering': ['route_template', 'sequence'],
                'unique_together': {('route_template', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='TrainRouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='Order of stops (1, 2, 3...)')),
                ('scheduled_arrival_time', models.TimeField(blank=True, help_text='Scheduled arrival time (null for source station)', null=True)),
                ('scheduled_departure_time', models.TimeField(blank=True, help_text='Scheduled departure time (null for destination station)', null=True)),
                ('actual_arrival_time', models.TimeField(blank=True, help_text='Actual arrival time (null for source station)', null=True)),
                ('actual_departure_time', models.TimeField(blank=True, help_text='Actual departure time (null for destination station)', null=True)),
                ('halt_minutes', models.PositiveIntegerField(default=0, help_text='Halt duration in minutes')),
                ('distance_from_source', models.FloatField(help_text='Distance from source station in km')),
                ('day_count', models.PositiveIntegerField(default=1, help_text='Day count (1 for same day, 2 for next day, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_stops', to='stations.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='trains.train')),
            ],
            options={
                'verbose_name': 'Train Route Stop',
                'verbose_name_plural': 'Train Route Stops',
                'ordering': ['train', 'sequence'],
                'unique_together': {('train', 'sequence')},
            },
        ),
    ]
