# Generated by Django 5.2.4 on 2025-07-22 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField()),
                ('is_bidirectional', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='stations.station')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='stations.station')),
            ],
            options={
                'db_table': 'route_graph',
                'unique_together': {('from_station', 'to_station', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='RouteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('local', 'local'), ('fast', 'fast')], max_length=20)),
                ('stops', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_starts', to='stations.station')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_ends', to='stations.station')),
            ],
            options={
                'db_table': 'templates',
                'unique_together': {('from_station', 'to_station', 'category')},
            },
        ),
    ]
