# Generated by Django 5.2.4 on 2025-07-06 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
        ('stations', '0002_alter_station_station_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteTemplateStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='Order of stops in the template')),
                ('distance_from_source', models.FloatField(help_text='Distance from source station in km')),
                ('estimated_halt_minutes', models.PositiveIntegerField(default=2, help_text='Estimated halt duration')),
                ('route_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_stops', to='routes.routetemplate')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_stops', to='stations.station')),
            ],
            options={
                'verbose_name': 'Route Template Stop',
                'verbose_name_plural': 'Route Template Stops',
                'ordering': ['route_template', 'sequence'],
                'unique_together': {('route_template', 'sequence')},
            },
        ),
    ]
