# Generated by Django 5.2.4 on 2025-07-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_routetemplatestop'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainroutestop',
            name='actual_arrival_time',
            field=models.TimeField(blank=True, help_text='Actual arrival time (null for source station)', null=True),
        ),
        migrations.AddField(
            model_name='trainroutestop',
            name='actual_departure_time',
            field=models.TimeField(blank=True, help_text='Actual departure time (null for destination station)', null=True),
        ),
        migrations.AddField(
            model_name='trainroutestop',
            name='scheduled_arrival_time',
            field=models.TimeField(blank=True, help_text='Scheduled arrival time (null for source station)', null=True),
        ),
        migrations.AddField(
            model_name='trainroutestop',
            name='scheduled_departure_time',
            field=models.TimeField(blank=True, help_text='Scheduled departure time (null for destination station)', null=True),
        ),
        migrations.AlterField(
            model_name='trainroutestop',
            name='arrival_time',
            field=models.TimeField(blank=True, help_text='[DEPRECATED] Use scheduled_arrival_time instead.', null=True),
        ),
        migrations.AlterField(
            model_name='trainroutestop',
            name='departure_time',
            field=models.TimeField(blank=True, help_text='[DEPRECATED] Use scheduled_departure_time instead.', null=True),
        ),
    ]
