# Generated by Django 5.2.4 on 2025-07-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_trainroutestop_actual_arrival_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainroutestop',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='trainroutestop',
            name='departure_time',
        ),
    ]
