# Generated by Django 5.2.4 on 2025-07-12 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_master',
            field=models.OneToOneField(blank=True, help_text='Assign a user with role=station_master and is_active=True.', limit_choices_to={'is_active': True, 'role': 'station_master'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station', to=settings.AUTH_USER_MODEL),
        ),
    ]
