# Generated by Django 5.2.4 on 2025-07-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_station_station_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the station is active or soft deleted'),
        ),
    ]
